In [368]:
import pandas as pd
from tqdm import tqdm
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [369]:
origin = pd.read_csv('cleaned_target_augmented.csv')

In [370]:
origin = origin.drop(['id'], axis=1)

In [371]:
vs = origin['sentence'].value_counts()

In [372]:
rp = vs[vs > 1].keys()

i = 0
rp_lst = [[] for _ in range(len(rp))]
for sen1 in tqdm(rp):
    for idx2, sen2 in enumerate(os):
        if sen1 == sen2:
            rp_lst[i].append(idx2)
    i += 1

100%|██████████| 5112/5112 [00:37<00:00, 137.20it/s]


In [374]:
overlap = pd.DataFrame()

for i in tqdm(range(len(rp_lst))):
    overlap = overlap.append(origin.loc[rp_lst[i]])

100%|██████████| 5112/5112 [00:04<00:00, 1127.58it/s]


In [464]:
idxs = [i for i in range(len(origin))]

for lst in rp_lst:
    for idx in lst:
        idxs.remove(idx)

In [527]:
origin.loc[idxs]['sentence'].value_counts()

트와이스 사나(미나토자키 사나·22) 옷 때문에 다현(김다현·21)이 놀랐다.                                                                                                                                                         1
1946년 8월 3일 이승만은 여운홍의 사회민주당(1946) 결성식에 참석하여 축사를 하였다.                                                                                                                                                1
바이에른 뮌헨의 감독으로 부임한 이후에도 분데스리가 3연패를 달성하면서 바르셀로나에서의 능력을 유감없이 보여주었지만 챔피언스리그에서는 세 시즌 연속으로 스페인 팀(레알 마드리드, FC 바르셀로나, 아틀레티코 마드리드)들과 4강전에서 만나 모두 패배하면서 챔피언스리그에서 두 번이나 우승했던 과르디올라 감독으로서는 조금 아쉬운 모습을 보여주었다.    1
한국판 기준 제152화 후편(기로로의 금단의 기억)에서는 기로로의 기억 속에 있는 히나타 나츠미의 얼굴을 자신의 얼굴로 바꾸는 등의 장난을 쳤다.                                                                                                                   1
문화왕후 김씨는 선주(善州, 지금의 경상북도 구미시 선산읍) 사람으로 뒤에 시중(侍中)을 추증받은 김원숭(金元崇)의 딸이다.                                                                                                                               1
          

In [ ]:
no_

In [539]:
skf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

no_rp_train = [[],[],[],[],[]]
no_rp_val = [[],[],[],[],[]]

i = 0
for train_index, test_index in skf.split(idxs, origin.loc[idxs]['label']):
    asd = no_rp_train[i]
    for j in train_index:
         asd.extend([idxs[j]])
    zxc = no_rp_val[i]
    for j in test_index:
         zxc.extend([idxs[j]])
    i += 1

In [541]:
for sen1 in tqdm(origin.loc[no_rp_train[0]]['sentence']):
    for sen2 in origin.loc[no_rp_val[0]]['sentence']:
        if sen1 == sen2:
            print(sen1)

100%|██████████| 18952/18952 [00:43<00:00, 439.29it/s]


In [544]:
rp_boss = []
for idx in rp_lst:
    rp_boss.append(idx[0])


In [545]:
rp_idxs = [i for i in range(len(rp_boss))]

In [550]:
rp_train_idx = [[],[],[],[],[]]
rp_val_idx = [[],[],[],[],[]]

i = 0
for train_index, test_index in skf.split(rp_idxs, origin.loc[rp_boss]['label']):
    asd = rp_train_idx[i]
    for j in train_index:
        asd.extend([rp_idxs[j]])
    zxc = rp_val_idx[i]
    for j in test_index:
        zxc.extend([rp_idxs[j]])
    i += 1

/opt/conda/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [556]:
rp_train = [[],[],[],[],[]]
rp_val = [[],[],[],[],[]]

i = 0
for rp in rp_train_idx:
    for rp_idx in rp:
        rp_train[i].extend(rp_lst[rp_idx])
    i += 1
    
i = 0
for rp in rp_val_idx:
    for rp_idx in rp:
        rp_val[i].extend(rp_lst[rp_idx])
    i += 1

In [567]:
fold_train = np.concatenate([no_rp_train[0], rp_train[0]])
fold_val = np.concatenate([no_rp_val[0], rp_val[0]])

In [568]:
fold_train = origin.loc[fold_train]
fold_val = origin.loc[fold_val]

In [569]:
for sen1 in tqdm(fold_val['sentence']):
    for sen2 in fold_train['sentence']:
        if sen1 == sen2:
            print(sen1)
            break

100%|██████████| 6967/6967 [00:31<00:00, 221.99it/s]


In [565]:
for i in range(5):
    fold_train = np.concatenate([no_rp_train[i], rp_train[i]])
    fold_val = np.concatenate([no_rp_val[i], rp_val[i]])
    
    fold_train = origin.loc[fold_train]
    fold_val = origin.loc[fold_val]
    
    fold_train.to_csv(f'fold{i}_train.csv')
    fold_val.to_csv(f'fold{i}_val.csv')

In [328]:
count = 0
for a in rp_lst:
    for b in a:
        count+=1
print(count)

11036


In [571]:
xcxc = {'asd':'123'}

In [573]:
xcxc.get('asd')

'123'

In [575]:
import torch

In [582]:
asd = torch.tensor([ 4,  0,  1,  0,  1,  0,  4,  6,  1,  1, 17, 10, 13,  0,  0, 17,  0,  1,
         0,  0,  0,  1, 20,  5,  0, 12, 15, 12,  0,  0,  0,  0])

In [585]:
asd.float().view(-1,32)

tensor([[ 4.,  0.,  1.,  0.,  1.,  0.,  4.,  6.,  1.,  1., 17., 10., 13.,  0.,
          0., 17.,  0.,  1.,  0.,  0.,  0.,  1., 20.,  5.,  0., 12., 15., 12.,
          0.,  0.,  0.,  0.]])

In [586]:
import torch
import torch.nn.functional as F

input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
loss.backward()

In [588]:
target

tensor([3, 2, 2])

In [589]:
input

tensor([[-0.1148, -1.1841, -0.1299, -2.8254,  1.5455],
        [-1.3652, -0.0629, -0.3447,  0.0806, -0.2065],
        [-0.1235,  0.0057, -0.7275,  1.0401, -0.1143]], requires_grad=True)

In [590]:
loss

tensor(2.9869, grad_fn=<NllLossBackward>)